config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  devise_for :users
  resources :tasks, except: :show do
    member do
      patch :update_task, to: 'tasks#update_task'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  ##### validations #####
  validates_presence_of :title
  validate :valid_state
  validate :valid_date, on: :create

  ##### callbacks #####
  before_create :set_sequence
 
  ##### public methods #####
  def valid_state
    errors.add(:status, "invalid state") unless ['pending', 'completed'].include?(self.status)
  end

  def valid_date
    errors.add(:due_date, "invalid date") if (self.due_date.present? && (self.due_date < Date.today))
  end

  def set_sequence #adds default sequence to task
    last_sequence = Task.where(user_id: self.user_id).pluck(:sequence).max
    self.sequence = last_sequence ? (last_sequence + 1) : 1
  end

  def formatted_date
    self.due_date ? self.due_date.strftime("%d/%m/%Y") : "--/--/--"
  end

  def update_seq_status(params)
    validate_sequence(params["prev_sequence"], params["next_sequence"])
    return if self.errors.present?
    update_sequence(params["prev_sequence"], params["next_sequence"])
    update_status(params["status"])
    self.save
  end

  # logic - when task dreg and drop down between task, 
  # following method calculates mean of prev & next task and use it as sequence.
  # becuase of this, only one (drag & dropping) tasks needs to update instead of multiple tasks
  def update_sequence(prev_sequence, next_sequence)
    if (prev_sequence && next_sequence)
      self.sequence = ((prev_sequence.to_f + next_sequence.to_f) / 2)
    elsif (prev_sequence && !next_sequence)
      self.sequence = prev_sequence.to_f + 1
    elsif (!prev_sequence && next_sequence)
      self.sequence = next_sequence.to_f - 1
    end
  end

  # only due and pending task are drag & dropped to completed task to mark them as complete.
  def update_status(status)
    self.status = status if status.present?
  end

  # to avoid calculation with non-numeric sequence.
  def validate_sequence(prev_sequence, next_sequence)
    errors.add(:sequence, "invalid sequence") if prev_sequence && !is_valid_number(prev_sequence)
    errors.add(:sequence, "invalid sequence") if next_sequence && !is_valid_number(next_sequence)
  end

  def is_valid_number(num)
    true if Float(num) rescue false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :tasks


  def user_name
    self.email.split("@").first.titlecase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_task, only: [:show, :edit, :update, :update_task, :destroy]

  def index
    @all_tasks = current_user.tasks.order("sequence ASC")
    respond_to do |format|
      format.html
    end
  end

  def new
    @task = Task.new
    respond_to do |format|
      format.html
    end
  end

  def create
    @task = current_user.tasks.build(tasks_params)
    respond_to do |format|
      if @task.save
        flash[:notice] = "Task successfully created"
        format.html{redirect_to tasks_path}
      else
        format.html{render :new}
      end
    end
  end

  def edit
    respond_to do |format|
      format.html
    end
  end

  def update
    respond_to do |format|
      if @task.update_attributes(tasks_params)
        flash[:notice] = "Task successfully updated"
        format.html{redirect_to tasks_path}
      else
        format.html{render :edit}
      end
    end
  end

  def update_task
    respond_to do |format|
      if @task.update_seq_status(params)
        response = {success: true, sequence: @task.sequence, status: @task.status, due_date: @task.formatted_date }
        format.json{render json: response}
      else
        response = { success: false, error: @task.errors.full_messages }
        format.json{render json: response}
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    def tasks_params
      params.require(:task).permit(:id, :title, :description, :due_date, :status, :sequence)
    end

    def get_task
      @task = current_user.tasks.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def due_tasks(tasks)
    tasks.select{|task| (task.status == 'pending') && (task.due_date == Date.today)}
  end

  def pending_tasks(tasks)
    tasks.select{|task| (task.status == 'pending') && (task.due_date != Date.today)}
  end

  def completed_tasks(tasks)
    tasks.select{|task| task.status == 'completed'}
  end
end

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "To-Do List", tasks_path, class: "navbar-brand mb-0 h1"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%- if current_user %>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <span class="nav-item nav-link active" >Hi, <%= current_user.user_name %> </span>
      </div>
    </div>
    <ul class="navbar-nav mr-auto justify-content-end">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.email %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Log Out", destroy_user_session_path, method: 'delete', class: "dropdown-item"%>
        </div>
      </li>
    </ul>
  <%- end %>
</nav>

app/views/layouts/_notice.html.erb
<%if flash.present?%>
  <%- flash.each do |name, msg| -%>
    <div class="alert alert-<%=(name == 'notice') ? 'success' : 'danger'%> alert-dismissible fade show" role= "alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <%- end -%> 
<%- end -%> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DripCapitalToDoAssignment</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "/layouts/nav_bar"%>
    <div class="container">
      <%= render "/layouts/notice"%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :due_date %><br />
    <%= f.date_field :due_date, class: "form-control" %>
  </div>

  <div class="actions">
    <%= link_to "Cancel", tasks_path, class: 'btn btn-secondary' %>
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/_list_task.html.erb
<div class="col-4">
  <h5 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted"><%= task_name.titlecase %> Tasks</span>
  </h5>
  <ul id="<%= task_name%>-list" class="connectedSortable list-group mb-2 p-2 border bg-light text-dark" data-type="<%= task_name%>">
    <%- unless tasks.present? %>
      <span class="emptyList">No tasks</span>
    <%- end %>
    <%- tasks.each do |task| %>
      <li class="list-group-item d-flex justify-content-between lh-condensed mb-2 p-2" data-sequence="<%=task.sequence%>" data-id="<%=task.id%>" data-status="<%= task_name%>">
        <div class="container">
          <div class="row">
            <div class="col-6">
              <h6 class="my-0"><%= task.title %></h6>
            </div>
            <div class="col-3">
              <small class="text-muted due_date"><%= task.formatted_date %></small>
            </div>
            <div class="col-3">
              <%= link_to edit_task_path(task) do%>
                <i class="fas fa-edit"></i>
              <%end%>
              <%= link_to task_path(task), method:"delete", remote: true, :data => {:confirm => "Are you sure you want to delete this task?"} do%>
                <i class="fas fa-trash"></i>
              <%end%>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <small class="text-muted"><%= task.description %></small>
            </div>
          </div>
        </div>
      </li>
    <%- end %>
  </ul>
</div>

app/views/tasks/destroy.js.erb
<%- if @task.errors.present? %>
  alert("An error occurred while deleting task, please try again.");
<%- else %>
  var ele = $('li.list-group-item[data-id="<%=@task.id%>"]')
  ele.remove();
  if (ele.siblings("li").length == 0) {
    $(this).find("h5").after("<span class='emptyList'>No tasks</span>")
  }
<%- end %>

app/views/tasks/edit.html.erb
<h2>Edit task : <%= @task.title%></h2>
<%= render "form" %>

app/views/tasks/index.html.erb
<div class="row mb-2 p-2">
  <%= link_to "Add Task", new_task_path, class: "btn btn-warning" %>
</div>
<div class="row">
  <%= render partial: 'list_task', locals: {tasks: due_tasks(@all_tasks), task_name: 'due'}%>
  <%= render partial: 'list_task', locals: {tasks: pending_tasks(@all_tasks), task_name: 'pending'}%>
  <%= render partial: 'list_task', locals: {tasks: completed_tasks(@all_tasks), task_name: 'completed'}%>
</div>

app/views/tasks/new.html.erb
<h2>New task</h2>
<%= render "form" %>